#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '3'
services:
  geode:
    image: 'geode:develop'
    hostname: locator-maeve
    entrypoint: 'sh'
    command: '-c /geode/scripts/forever'
    networks:
      geode-sni-test:
        aliases:
          - locator-maeve
    volumes:
      # NOTE: Volumes are writable (no :ro flag) to allow dynamic certificate generation
      # at test runtime. The test generates keystores with actual Docker-assigned IP addresses
      # before starting Geode processes, as Jetty 12 requires IP SANs for RFC 6125 compliance.
      - ./geode-config:/geode/config
      - ./scripts:/geode/scripts
  geode-server-clementine:
    image: 'geode:develop'
    hostname: server-clementine
    entrypoint: 'sh'
    command: '-c /geode/scripts/forever'
    networks:
      geode-sni-test:
        aliases:
          - server-clementine
    volumes:
      # NOTE: Volumes are writable to allow dynamic certificate generation (see geode service above)
      - ./geode-config:/geode/config
      - ./scripts:/geode/scripts
  geode-server-dolores:
    image: 'geode:develop'
    hostname: server-dolores
    entrypoint: 'sh'
    command: '-c /geode/scripts/forever'
    networks:
      geode-sni-test:
        aliases:
          - server-dolores
    volumes:
      # NOTE: Volumes are writable to allow dynamic certificate generation (see geode service above)
      - ./geode-config:/geode/config
      - ./scripts:/geode/scripts
  haproxy:
    image: 'haproxy:2.1'
    depends_on:
      - geode
      - geode-server-dolores
      - geode-server-clementine
    ports:
      - "15443:15443"
    networks:
      geode-sni-test:
    volumes:
      - ./dual-server-haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
networks:
  geode-sni-test:
    name: geode-sni-test

